import './main.scss'
import confirmAge from './components/confirm-age-modal/confirm-age.js'
import entry from './components/entry/entry.js'
import changeLanguage from './components/header/change-language.js'
import form from './components/form/form.js'
